### PR TITLE
Fix some cases where Rename hasn't picked up by class registration

### LINKED ISSUE #177: Register Singleton fails to compile
Due to changes in base class handling singleton registration code now fails.

register.d around line 628 now should look like this
`Engine.registerSingleton(snPropName, storageField._godot_base);`

### PR DESCRIPTION
**Pull request by Superbelko**
Fix #177 #178

Singleton registration now uses `object._godot_base` since there is no guarantee that user classes will have `alias this`, and add some missing `@Rename` cases.

### CODE REVIEW

File: src/godot/api/wrap.d [hunk 1]
```diff
@@ -635,7 +635,17 @@ package(godot) PropertyInfo makePropertyInfo(alias T, string Name)() {
...
 
-    static if (Variant.variantTypeOf!T == VariantType.object) {
+    // this will probably require same fix for other conainers like TypedArray
+    alias typeRenameAttr = getUDAs!(NonRef!T, Rename); // Ref itself has no attributes
+    static if (typeRenameAttr.length)
+        enum Rename typeRenamed = typeRenameAttr[0];
+    else
+        enum Rename typeRenamed = Rename.init;
+    static if (typeRenamed.name) {
+        pragma(msg, typeRenamed);
```
Comment (Superbelko) [inline src/godot/api/wrap.d:645]: Oh no...
