### PR TITLE
Register GodotScripts as GC scannable ranges

### LINKED ISSUE #200: User-written scripts not registered to the GC, leading to confusing memory corruption.
Godot has it's own memory management, so there is no need for the D garbage collector to collect the script classes themselves.

However, consider a regular D array, allocated on the heap by the script:

```D
class MissionResult : GodotScript!Node
{   alias owner this;
    int[] hits;

    @Method void _ready()
    {   if (Engine.isEditorHint()) return;
        hits = new int[](targetNames.length);
    }
}
```

This results in memory corruption! Since the D GC doesn't know about the `MissionResult` instance, it won't find any reference to the ints referred to by `hits`, and will therefore collect them the next time it needs to collect. It's especially confusing since `hits` usually seems to work right at first, but will then get strange values and at some point crash.

Ideally, there would be a global pool of `Object` references that the GC knows about, and `createFunc` and `destroyFunc` templates would add/remove references to the scripts to/from the said pool.

Now, I understand that Godot is designed to work without a garbage collector, so it might not be desirable to do this for all scripts. I think it should be done by default, though. The times when the GC has to be avoided are relatively rare, but the dangling pointer bugs with the present situation are really likely to happen and confusing when they do. Yes, the Godot data structures are good workarounds that don't suffer from this problem, but still.

### PR DESCRIPTION
**Pull request by Superbelko**
Close #200

### CODE REVIEW

File: src/godot/api/udas.d [hunk 1]
```diff
@@ -233,3 +233,19 @@ A UDA to mark a static field to be used by Godot as a global singleton object.
...
 }
+
+/++ 
+Advanced attribute that tells GC to ignore this class when scanning memory for pointers.
+
+Note that GodotScript objects are not allocated by GC and 
+uses GC.addRange mechanism to tell GC to scan memory for pointers inside that object.
+This attribute has effect that any pointer to a GC allocated memory will become a non-owning reference,
+and will no longer prevent garbage collection despite that there might still be live references in it.
+Simply put, marked objects may have its GC managed data collected when you don't expect it.
```
Comment (dukc) [inline src/godot/api/udas.d:244]: The terminology is inaccurate here, making it confusing IMO. It's not about telling the GC to ignore anything - were you to `new` the godot script it would be registered normally, attribute or no. What about:
```D
Advanced attribute that tells Godot memory allocation funtions to not register it to D garbage collector.
```

Also, an owning pointer as I understand it means something like Godot `Node`s or `std.typecons.Unique` - that is, when you delete them the pointee gets deleted too. This means normal D references are always non-owning (unless you enable ownership/borrowing and add `@live` to your function). I think the correct term here is "weak reference" .

**Review by dukc — COMMENTED** [review]
Thanks - exactly what I requested!

File: src/godot/api/udas.d (hunk 1 above)
Comment (Superbelko) [reply src/godot/api/udas.d:244]: Well ok, the first line is indeed isn't clear enough.

But the rest is depends, I guess.
The comment explains what it does.
Technically the runtime isn't aware there is typed block of memory that may contain GC allocated memory, so by not letting it know about them is basically same as saying "do not scan" this.

This sort of "weak reference" is basically useless if there is no way to check its validity (there isn't), which is why we had such confusing bugs that looks like memory corruption.
